
<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$storeInformation = $objectManager->create('Magento\Store\Model\Information');

$store = $objectManager->create('Magento\Store\Model\Store');

$storeInfo = $storeInformation->getStoreInformationObject($store);

$phone = $storeInfo->getPhone();
$email = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('trans_email/ident_general/email');

?>
<div class="phone-contact">
	<p class="text-phone">PHONE</p><p class="phone-number"><a href="tel:1800 807 604"><?php echo $phone; ?></a></p>
</div>
<div class="email-contact">
	<p class="text-email">EMAIL</p><p class="email-number"><a href="mailto:sales@reefe.com.au"><?php echo $email; ?></a></p>
</div>