
<script src='https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit&hl=en'></script>

<div id="recaptcha_element_contacts"></div>

<script type="text/javascript">
	var onloadCallback = function() {
		grecaptcha.render('recaptcha_element_contacts', {
			'sitekey' : '6LePG20UAAAAAK_70_6shm6cRqVA6xzXOmzNt6nj'
		});       
	}; 
	window.onload = function() { 
		jQuery( '#btn-contacts').click(function(){
			var response = grecaptcha.getResponse();
			if (response.length === 0){
				alert('Please complete the reCAPTCHA!');
				return false;
			}else {
				jQuery('#btn-contacts').submit();
			}
		});
	};
</script>



<!-- cách 2 -->
<script src='https://www.google.com/recaptcha/api.js?hl=en'></script>

<div class="g-recaptcha required-entry" data-sitekey="6Ldti0UUAAAAAIfRbB2tL0PTnYV8KuTYIyFlOABV"></div>

<script type="text/javascript">
    window.onload = function() {
     var recaptcha = document.forms["contactForm"]["g-recaptcha-response"];
     recaptcha.required = true;
     recaptcha.oninvalid = function(e) {
      alert("Please complete the reCAPTCHA!");
  }
}
</script> 