<?php
/** 
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * @var $block \Manadev\LayeredNavigation\Blocks\Navigation
 *
 * Based on app/code/Magento/LayeredNavigation/view/frontend/templates/layer/view.phtml (diff to check
 * what has changed).
 */
?>

<?php if ($block->isVisible()): ?>
    <div class="block filter mana-filter-block" data-mage-init='{ "Manadev_LayeredNavigation/js/NavigationView": {} }'>
        <div class="block-content filter-content">
            <?php /* if ($block->hasState() && $block->isAppliedFilterVisible()) : ?>
                <div class="filter-current">
                    <strong class="block-subtitle filter-current-subtitle" role="heading" aria-level="2" data-count="<?php echo $block->getAppliedOptionCount() ?>"><?php echo __('Now Shopping by') ?></strong>
                    <ol class="items">
                        <?php foreach ($block->getAppliedFilters() as $engineFilter): ?>
                            <?php foreach ($engineFilter->getAppliedItems() as $item) : ?>
                                <li class="item"><?php echo $block->renderAppliedItem($engineFilter, $item) ?></li>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
            <?php endif; */ ?>
            <?php            
            $selectedFilter = [];
            $params = $this->getRequest()->getParams();
            foreach ($params as $key => $value) {
                $selectedFilter[] = $key;
            }         
            ?>

            <dl class="filter-options" id="narrow-by-list">
                <?php foreach ($block->getFilters() as $filter): ?>
                    <div class="filter-options-contain <?php if(in_array($filter->getFilter()->getData('param_name'), $selectedFilter)): ?>is_open<?php endif; ?>">
                        <?php $cssClass = $block->getData('css_prefix') . '-filter-' . str_replace('_', '-', $filter->getFilter()->getData('param_name')) ?>
                        <dt role="heading" aria-level="3" class="filter-options-title <?php echo $cssClass ?>"><?php echo $block->escapeHtml(__($filter->getName())) ?></dt>
                        <dd class="filter-options-content <?php echo $cssClass ?>" <?php if(in_array($filter->getFilter()->getData('param_name'), $selectedFilter)): ?>style="display: block;"<?php endif; ?>><?php echo $block->renderFilter($filter) ?></dd>
                    </div>
                <?php endforeach; ?> 
            </dl> 
            <?php if ($block->hasState() && $block->isAppliedFilterVisible()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?php echo $block->getClearUrl() ?>"<?php echo $block->getClearLinkAttributes() ?> class="action clear filter-clear"><span><?php echo __('Clear') ?></span>
                        <i class="fas fa-times"></i>
                    </a>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>