
<!-- /** @var \Magento\Catalog\Block\Product\Gallery $block */ -->

<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$categoryIdRoot = 2;
$categoryCollection = $objectManager->create('Magento\Catalog\Model\Category')->getCollection()->addAttributeToSelect('*');
$categoryCollection->addAttributeToFilter('parent_id', $categoryIdRoot);
$categoryCollection->addAttributeToFilter('is_active', 1);
// $categoryCollection->addAttributeToFilter('include_in_menu', 1);
$categoryCollection->setOrder('position', 'ASC');
?>

<div class="list-categories">
	<ul class="list-category-parent">
		<!-- Check have category -> show -->
		<?php if (count($categoryCollection)): ?>
			<?php foreach ($categoryCollection as $category): ?>
				<?php $subcats = $category->getChildrenCategories(); ?>
				<?php $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId()); ?>
				<!-- Check have subcategory -> show -->
				<?php if (count($subcats)): ?>
					<li class="level-0">
						<a href="<?php echo $category->getUrl(); ?>">
							<!-- Check have thumbnail -> show image -->
							<?php if ($_category->getThumbnail()): ?>
								<img src="<?php echo  $mediaUrl.'catalog/category/'.$_category->getThumbnail(); ?>" alt="<?php echo $category->getName(); ?>">
							<?php else: ?>
								<img src="<?php echo $mediaUrl; ?>wysiwyg/small_image.jpg" alt="<?php echo $category->getName(); ?>">
							<?php endif; ?>
							<span><?php echo $category->getName(); ?></span>
						</a>
						<ul class="list-category-child">
							<?php foreach ($subcats as $subcat): ?>
								<?php $_subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId()); ?>
								<li class="level-1">
									<a href="<?php echo $subcat->getUrl() ?>" title="<?php echo $subcat->getName(); ?>">
										<?php if ($_subCategory->getThumbnail()): ?>
											<img src="<?php echo  $mediaUrl.'catalog/category/'.$_subCategory->getThumbnail(); ?>" alt="<?php echo $subcat->getName(); ?>">
										<?php else: ?>
											<img src="<?php echo $mediaUrl; ?>wysiwyg/small_image.jpg" alt="<?php echo $subcat->getName(); ?>">
										<?php endif; ?>
										<span>
											<?php echo $subcat->getName(); ?>
										</span>
									</a>
								</li>
							<?php endforeach ?>
						</ul>
					</li>
				<?php endif ?>
				
			<?php endforeach ?>
		<?php endif ?>		
	</ul>
</div>
<style type="text/css">
.cms-index-index #maincontent > .row{
	margin-left: -15px;
	margin-right: -15px;
}
.block-bottom-slider .slider_mgs_carousel.owl-carousel{
	padding: 0 15px;
}	
.list-categories ul.list-category-parent{
	position: relative;
}
.list-categories ul.list-category-parent li.level-0{
	width: 16.6667%;
	float: left;
}
.list-categories ul.list-category-parent li{
	border-right: 1px solid #fff;
	border-top: 1px solid #fff;
}
.list-categories ul.list-category-parent li:last-child{
	border: none;
}
.list-categories ul.list-category-parent li span{
	font-size: 16px;
	font-weight: 400;
	color: #0099d2;
	line-height: 36px;
	padding: 0 10px;
	font-family: 'Oswald', sans-serif;
	width: 100%;
	display: block;
	position: relative;
}
.list-categories ul.list-category-parent li:hover>span{
	font-weight: 500;
}
.list-categories ul.list-category-parent li.level-0 img{
	width: 100%;
	min-height: 180px;
	max-height: 180px;
}
.list-categories ul.list-category-parent li.level-0 span:before{ 
	content: '';
	width: 0; 
	height: 0; 
	border-top: 15px solid transparent;
	border-bottom: 0px solid transparent; 
	border-right:15px solid #0099d2; 
	position: absolute;
	right: 10px;
	top: 50%;
	transform: translateY(-50%);
}
.list-categories ul.list-category-parent li.level-0 {
	width: 16.6667%;
	float: left;
}
.list-categories li  ul.list-category-child{
	position: absolute;
	display: none;
}
.list-categories li.is_active  ul.list-category-child{
	display: block;
}
.list-categories ul.list-category-parent li.level-1{
	width: 100%;
	max-width: 170px;
	float: left;
}
.list-categories ul.list-category-parent li.level-1 img{
	width: 100%;
	min-height: 105px;
	max-height: 105px;
}
</style>
<script type="text/javascript">
	require([
		'jquery'
		], function ($) {
			$(document).ready(function(){
				$('.list-category-parent li.level-0:first-child').addClass('is_active');
				$('.list-category-parent li.level-0').hover(function(){
					$('.list-category-parent li.level-0').removeClass('is_active');
					$(this).addClass('is_active');
				});
			});
		});
	</script> 