<?php
$params = $this->getRequest()->getParams();
$helper = $this->helper('MGS\Brand\Helper\Data');
$collection = $block->getCollection();
if ($this->getConfig('list_page_settings/small_image_width') != '') {
    $width = $this->getConfig('list_page_settings/small_image_width');
} else {
    $width = 240;
}
if ($this->getConfig('list_page_settings/small_image_height') != '') {
    $height = $this->getConfig('list_page_settings/small_image_height');
} else {
    $height = 180;
}
?>
<div class="shop-by-brand">
    <?php if ($helper->getConfig('list_page_settings/description') != ''): ?>
        <div class="description">
            <?php echo $helper->getConfig('list_page_settings/description'); ?>
        </div>
    <?php endif; ?>
    <?php if ($helper->getConfig('list_page_settings/show_featured_brands')): ?>
        <?php echo $block->getChildHtml('brand_list_featured'); ?>
    <?php endif; ?>
    <?php echo $block->getChildHtml('brand_search'); ?>
    <?php echo $block->getChildHtml('brand_filter_by_character'); ?>
    <div class="all-brands">
        <?php $flagDigit = false; ?>
        <?php if ($collection->count()): ?>
            <div class="content">
                <ul class="brand-list">
                    <?php $brandArr = array() ;?>    
                    <?php $brandCount = array(); ?>               
                    <?php foreach ($collection as $brand): ?>
                        <?php   
                        $brandSmallImage = $brand ->getSmallImageUrl();    
                        $brandName = $brand->getName();
                        $brandUrl = $brand ->getUrl(); 
                        $brandArr[$brandName] = $brandUrl;
                        $brandCount[$brandName] = $block->getProductCount($brand); ?>
                    <?php endforeach; ?>
                    <?php ksort($brandArr);  ?>
                    <?php $batch = '';
                    $fisrt = reset($brandArr);
                    $previous = strtoupper(substr("$fisrt", 0, 1));
                    $count = count($brandArr);
                    $i=0; ?>    
                        <?php foreach ($brandArr as $brandKey => $brandValue):?>  
                            <?php 
                            $i++;
                            $firstLetter = strtoupper(substr($brandKey, 0, 1));
                            ?>
                            <?php if($previous !== $firstLetter) : ?>
                                <?php $previous = $firstLetter; ?>
                                <li class="item">
                                    <div class="brand-content">
                                        <?php if ($this->getConfig('list_page_settings/show_brand_name')): ?>
                                            <h3 class="brand-title"><?php echo $previous; ?></h3>
                                                <a title="<?php echo $brandKey; ?>" href="<?php echo $brandValue; ?>" class="brand-name">
                                                    <?php echo $brandKey; ?>
                                                    <?php if ($this->getConfig('list_page_settings/show_product_count')): ?>
                                                        <span><?php echo __('(%1)', $brandCount[$brandKey]); ?></span><br>
                                                    <?php endif; ?>
                                                </a>
                                        <?php endif; ?>
                                <?php else: ?>
                                        <a title="<?php echo $brandKey; ?>" href="<?php echo $brandValue; ?>" class="brand-name">
                                            <?php echo $brandKey; ?>
                                            <?php if ($this->getConfig('list_page_settings/show_product_count')): ?>
                                                <span><?php echo __('(%1)', $brandCount[$brandKey]); ?></span>
                                            <?php endif; ?><br>
                                        </a>
                            <?php endif; ?>

                            <?php if($i == $count): ?>
                                    </div>
                                </li>                         
                        <?php endif; ?>
                    <?php endforeach; ?> 
                    <li class="clear"></li>                  
                </ul>
            </div>
<!--             <?php if (isset($params['char']) && $params['char'] != '' && $params['char'] == '0-9' && $flagDigit == false): ?>
                <script type="text/javascript">
                    require(['jquery'], function ($) {
                        $('ul.brand-list').hide();
                    });
                </script>
                <div class="message">
                    <div><?php echo __('Have no brands.') ?></div>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <div class="message">
                <div><?php echo __('Have no brands.') ?></div>
            </div>
        <?php endif; ?> -->
    </div>
</div>
<?php echo $this->getPagerHtml() ?>
