<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Category left navigation
 *
 * @var $block \Magento\Catalog\Block\Navigation
 */
?>
<?php if (!$block->getCategory()) {
    return;
} ?>
<?php $_categories = $block->getCurrentChildCategories(); ?>
<?php $_categoriess = $block->getCurrentCategory(); ?>
<?php $_count = is_array($_categories) ? count($_categories) : $_categories->count(); ?>
<?php if ($_count): ?>
    <!-- <div class="name-cate">
        <h1>Name Category</h1>
        <?php foreach ($_categoriess as $_categorys): ?>
            <h2><?php echo $_categorys->getName(); ?></h2>
        <?php endforeach ?>
        <h6>ok</h6>
    </div> -->
    <div class="block filter">
        <div class="content">
            <dl class="options" id="narrow-by-list2">
                <dd>
                    <ol class="items">
                        <?php foreach ($_categories as $_category): ?>
                            <?php if ($_category->getIsActive()): ?>
                                <li class="item">
                                    <a href="<?= /* @escapeNotVerified */ $block->getCategoryUrl($_category) ?>"<?php if ($block->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?= $block->escapeHtml($_category->getName()) ?></a>
                                    <!-- <span class="count"><?= /* @escapeNotVerified */ $_category->getProductCount() ?></span> -->
                                </li>
                            <?php endif; ?>
                        <?php endforeach ?>
                    </ol>
                </dd>
            </dl>
        </div>
    </div>
<?php endif; ?>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
/* Get base url with index When index.php enable at Url */
 $baseUrl = $storeManager->getStore()->getBaseUrl();
/* Result  http://www.example.com/ or http://www.example.com/index.php  depends SEo rewite settng*/
/* it always give the URL without Index.php either index.php enable for Url */ 
$baseUrlWithOutIndexPhp = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
// $baseUrl  result = http://example.com/

/* It is give url with index.php whenever  seo rewrite not enable mean when  Index.php show at Url  */

$linkUrl= $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

 /* $linkUrl  result = http://example.com/index.php/
         whenever  seo rewrite not enable mean when  Index.php show at Url
        
        but when  SEO Rewrite enabled
        
        Then it show result = http://example.com/
 
 */

        $statiContenteUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_STATIC);
/* Result $statiContenteUrl = http://example.com/pub/static/version1507042743/
    In this part  version1507042743 is 1507042743 static content version which dynamcically created
*/
 $mediaUrl =  $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
/* Result $mediaUrl = http://example.com/pub/media/

*/
